### ISSUE TITLE
Can I use Summary row?

### ISSUE THREAD

**Issue by Bombay** [future-architect/cheetah-grid#125]
Can I use a summary row?

I do not need a calculated summary row, but I need a summary row that is fixed and scrollable with its contents.

Thank you for great grid!

**Comment by ota-meshi** [comment]
Thank you for this issue!

Would you like to display fixed the footer row?
Now this grid does not have that feature.

> Thank you for great grid!
I'm glad! Thank you!

**Comment by ota-meshi** [comment]
As it is included in issue #84, I close this issue.
