### ISSUE TITLE
Is there a way to have select an entire column?

### ISSUE THREAD

**Issue by nlipsyc** [future-architect/cheetah-grid#131]
I would like to have the ability to add a checkbox next to the column header name that would "select" the column and add a style on it.  I can't seem to find a way to add a checkbox (or any piece of non-text) to the header.  I'd be happy to contribute if this functionality isn't already there.  I doesn't seem like it would be too bad to add in a boolean input in `c-grid-input` column header and have it trigger `header-action`.  I'm working in Vue for this.

**Comment by ota-meshi** [comment]
Thank you for this issue!

I recently added a feature to draw a checkbox in the header to `cheetah-grid`.
However, `vue-cheetah-grid` does not seem to work well.
I will lookup the cause and fix it. so please wait.

**Comment by ota-meshi** [comment]
I fixed some bugs and released them. (v0.11.x)
And I made sample code on the following link.

https://future-architect.github.io/cheetah-grid/0.11/demos/faq/header_check.html#using-vue-js

**Comment by nlipsyc** [comment]
Thank you @ota-meshi , that's fantastic!
