### ISSUE TITLE
How to set the padding of the header

### ISSUE THREAD

**Issue by hywww** [future-architect/cheetah-grid#143]

**Comment by ota-meshi** [comment]
@hywww Thank you for this issue.
There is no API to set the padding style in the header of the cheetah grid now.

**Comment by lesonky** [comment]
You can add a space to your header caption, just like this
(in vue component)
```
:caption="` ${header.label} `"
```

**Comment by hywww** [comment]
您好，您的邮件我已收到，我会尽快给您回复。
