### ISSUE TITLE
how can i get all columns width when i resized the column?

### ISSUE THREAD

**Issue by Trubasa** [future-architect/cheetah-grid#159]
in the event below，i can't get the info of the column
`grid.listen(RESIZE_COLUMN, (...args) => log(RESIZE_COLUMN, args));`

and i try to get grid.header,but it is  the outmoded data

**Comment by ota-meshi** [comment]
Thank you for this issue!

You can gets the new column width definition with `grid.getColWidth(col)`.

**Comment by Trubasa** [comment]
Thanks!
