### ISSUE TITLE
I want an API to set the value of defaultRowHeight in Vue.

### ISSUE THREAD

**Issue by snm2048** [future-architect/cheetah-grid#165]
Hi..

I use 'multilinetext' in c-grid-column of vue components.
Please provide an API to set the value of defaultRowHeight because it will be missed if you display more than 3 rows.

Thank you.

**Comment by ota-meshi** [comment]
I added the `default-row-height` property in version 0.14.
https://future-architect.github.io/cheetah-grid/documents/api/vue/components/CGrid.html#optional-properties
