### ISSUE TITLE
Custom sort function does not work.

### ISSUE THREAD

**Issue by shin-nakamura** [future-architect/cheetah-grid#168]
After upgrading version v0.9.0 -> v0.13.8, custom sort function does not work.

https://future-architect.github.io/cheetah-grid/documents/api/js/advanced_header/column_sort.html#sort-by-column

`this._sort` in `_executeSort` method(at cheetahGrid.es5.js) seems to be `undefined`.
Is there something wrong with the implementation?
It worked without problems before upgrading.

**Comment by ota-meshi** [comment]
Thank you for this issue!
I have released 0.13.9 that fixes this issue.
