### ISSUE TITLE
https://github.com/livelyPeng/pl-table 流畅渲染万级数据并不会影响到 element-ui el-table组件的原有功能，并且新增了一些功能

### ISSUE THREAD

**Issue by livelyPeng** [future-architect/cheetah-grid#173]
https://github.com/livelyPeng/pl-table 流畅渲染万级数据并不会影响到 element-ui el-table组件的原有功能，并且新增了一些功能

**Comment by ota-meshi** [comment]
私は中国語がわかりません。問題がある場合、日本語か英語でissueを開いてください。
このissueは閉じます。
