### ISSUE TITLE
how to set opacity of background？

### ISSUE THREAD

**Issue by doubleKGe** [future-architect/cheetah-grid#176]
Hi，I want to use the background color with transparency. I don't know how to set it

**Comment by doubleKGe** [comment]
If I set the background color with transparency, when I scroll or click, the layers will overlap and the transparency will fail

**Comment by ota-meshi** [comment]
Thank you for this issue.

Opacity cannot be set for the background.

Also, with the current this grid engine, it is very difficult to set the opacity for the background, so there is no plan to deal with it.
