### ISSUE TITLE
Sort reset, sort result, sort event

### ISSUE THREAD

**Issue by Olivier61** [future-architect/cheetah-grid#181]
Hi,

1. After resetting sort, the sort arrow is reset but the grid does not return to original order
```
 grid.sortState = null;
 grid.invalidate();
// does not restore the data to original order
```
2. Is there a way to get the relation between the original row id and the row id after sort ?
3. Is there a way to get an event when the grid is sorted ?

Thanks !

**Comment by ota-meshi** [comment]
Thank you for this issue.

1. There is no API to reset the sorting of the records in the grid, so you need to reset the "records" property.

2. There is no API to get the relation between the original row id and the row id after sort.

3. You can listen for changes in the header values by listening to `cheetahGrid.ListGrid.EVENT_TYPE.CHANGED_HEADER_VALUE`. The header values includes the sort status.
