### ISSUE TITLE
wrong checkbox style after page was mounted

### ISSUE THREAD

**Issue by nttd-haohe** [future-architect/cheetah-grid#217]
*  **Question one:**
After page was mounted, the status of check box looks like wrong.  
![image](https://user-images.githubusercontent.com/32086985/77248965-ba8e8880-6c78-11ea-915a-cda137a5a8b7.png)
If I scroll the table, the status of check boxes were redrewed to right status. Please refer to the image.  
![image](https://user-images.githubusercontent.com/32086985/77249017-1fe27980-6c79-11ea-9157-c3ad943bd3bc.png)
*  **Question two:**  
Is there a way to change the style of check box. I want to display checkbox with different styles according to status (disabled or not).  
I try to define a function in theme's checkbox node like below.  But I found that this method is only normal at the end of the page loaded. When I try to change the state of the check box through the function (from enable to disabled = true), the style of the check box cannot be changed.
```javascript
   checkbox: {
      uncheckBgColor(args: any): any {
        if (
          args.grid.header[args.col - 1].columnType != 'check' ||
          typeof args.grid.header[args.col - 1].action.disabled != 'function'
        ) {
          return 'rgb(255, 255, 255)';
        }
        if (args.grid.header[args.col - 1].action.disabled(args.grid.records[args.row - 1])) {
          return 'rgb(128, 128, 128)';
        } else {
          return 'rgb(255, 255, 255)';
        }
      },
      checkBgColor(args: any): any {
        if (
          args.grid.header[args.col - 1].columnType != 'check' ||
          typeof args.grid.header[args.col - 1].action.disabled != 'function'
        ) {
          return 'rgb(0, 0, 0)';
        }
        if (args.grid.header[args.col - 1].action.disabled(args.grid.records[args.row - 1])) {
          return 'rgb(128, 128, 128)';
        } else {
          return 'rgb(0, 0, 0)';
        }
      },
      borderColor(args: any): any {
        if (
          args.grid.header[args.col - 1].columnType != 'check' ||
          typeof args.grid.header[args.col - 1].action.disabled != 'function'
        ) {
          return 'rgb(0, 153, 255)';
        }
        if (args.grid.header[args.col - 1].action.disabled(args.grid.records[args.row - 1])) {
          return 'rgb(128, 128, 128)';
        } else {
          return 'rgb(0, 153, 255)';
        }
      },
    }
```  
**Thanks for your work. Best Regarding.**

**Comment by nttd-haohe** [comment]
I resolved the question tow like below. Just define style in `new cheetahGrid.ListGrid()`. But the source was redundancy. I must define style for all checkbox.  
```javascript
header: [
          {
            field: 'printChk',
            caption: 'test',
            width: 34,
            columnType: 'check',
            action: printCheckEditorAction as any,
            headerStyle: { textAlign: 'center' },
            headerType: 'multilinetext' as 'default',
            style(rec): any {
              let uncheckBgColor;
              let checkBgColor;
              let borderColor;
              if (!rec.printEnableFlg) {
                uncheckBgColor = 'rgb(128, 128, 128)';
                checkBgColor = 'rgb(128, 128, 128)';
                borderColor = 'rgb(128, 128, 128)';
              } else {
                uncheckBgColor = 'rgb(255, 255, 255)';
                checkBgColor = 'rgb(0, 0, 0)';
                borderColor = 'rgb(0, 153, 255)';
              }
              return {
                uncheckBgColor: uncheckBgColor,
                checkBgColor: checkBgColor,
                borderColor: borderColor,
              };
            },
          },
]
```

**Comment by ota-meshi** [comment]
Thank you for this issue. Can you share a minimal repository to reproduce the this issue?

**Comment by nttd-haohe** [comment]
I fixed it. Just add `grid.invalidate()` to `updated ` method.
Thanks for your feedback.

**Comment by lkiersey** [comment]
> I resolved the question tow like below. Just define style in `new cheetahGrid.ListGrid()`. But the source was redundancy. I must define style for all checkbox.
> 
> ```js
> header: [
>           {
>             field: 'printChk',
>             caption: 'test',
>             width: 34,
>             columnType: 'check',
>             action: printCheckEditorAction as any,
>             headerStyle: { textAlign: 'center' },
>             headerType: 'multilinetext' as 'default',
>             style(rec): any {
>               let uncheckBgColor;
>               let checkBgColor;
>               let borderColor;
>               if (!rec.printEnableFlg) {
>                 uncheckBgColor = 'rgb(128, 128, 128)';
>                 checkBgColor = 'rgb(128, 128, 128)';
>                 borderColor = 'rgb(128, 128, 128)';
>               } else {
>                 uncheckBgColor = 'rgb(255, 255, 255)';
>                 checkBgColor = 'rgb(0, 0, 0)';
>                 borderColor = 'rgb(0, 153, 255)';
>               }
>               return {
>                 uncheckBgColor: uncheckBgColor,
>                 checkBgColor: checkBgColor,
>                 borderColor: borderColor,
>               };
>             },
>           },
> ]
> ```

Any chance you can post a working example of this? I cant seem to get it to work
