### ISSUE TITLE
feature requests: can the rows of the grid change background color when I move the mouse in?

### ISSUE THREAD

**Issue by lusase** [future-architect/cheetah-grid#221]
can the rows of the grid change background color when I move the mouse in?

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

I think it's possible to use the `MOUSEENTER_CELL` and `MOUSELEAVE_CELL` events to watching the mouse position, change the style of the cell and then call `invalidate`.

There is no plan to provide it as a standard API.
