### ISSUE TITLE
How to select and highlight entire row? Not cells

### ISSUE THREAD

**Issue by caracal7** [future-architect/cheetah-grid#223]
How to select and highlight entire row? Not cells....
And how to set/remove selection programmatically?

Fantastic grid but without this features is unusable for me...

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

Do you want to select rows with checkboxes?
If so, I think you can change the style of the cell with the value of the check, watch the toggle and call `invalidate`.

```js
const grid = new cheetahGrid.ListGrid({
  header: [
    { field: 'selected', columnType: 'check', action: 'check' }
    {
      field: '...',
      style(rec) {
        return {
          bgColor: rec.selected ? '#ddf' : undefined,
        };
      }
    },
    // ...
}

grid.listen(cheetahGrid.ListGrid.EVENT_TYPE.CHANGED_VALUE, () => grid.invalidate());
```

Also, to change the select, change the value of the record and call `invalidate`.

```js
record.selected = false
grid.invalidate()
```
