### ISSUE TITLE
columnType:'image' isn't working with data:image/jpeg;base64

### ISSUE THREAD

**Issue by Wave89** [future-architect/cheetah-grid#225]
I tried the example for comlumn type image: https://future-architect.github.io/cheetah-grid/documents/api/js/column_types/ImageColumn.html with an base64 picture. 

2 problems:
- The picture appears only after clicking the area
- style: {imageSizing: 'keep-aspect-ratio'} isn't working

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

I will check this issue.

**Comment by ota-meshi** [comment]
Hmm... I was unable to reproduce this issue. Can you share a minimal repository to reproduce your issue?

**Comment by Wave89** [comment]
Hey, I'm sorry. I double checked it and found the errors on my configuration side. Sorry. Issue can be closed.

**Comment by ota-meshi** [comment]
OK. I'm happy this worked for you.
