### ISSUE TITLE
Feature request: header-type of icon

### ISSUE THREAD

**Issue by Amndeep7** [future-architect/cheetah-grid#246]
Could the header "caption" be an icon similar to how a cell in an IconColumn can be one or more icons?

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

Currently, you cannot place your favorite icon in the header. We need to make changes to the grid.

**Comment by ota-meshi** [comment]
Supported in [v1.4.0](https://github.com/future-architect/cheetah-grid/releases/tag/v1.4.0).
