### ISSUE TITLE
Bug report: headers aren't always re-rendered properly

### ISSUE THREAD

**Issue by Amndeep7** [future-architect/cheetah-grid#247]
When you click on a header in order to do a 'check' event, sometimes the other headers aren't updated as well.  

Please see this repo as an example and full explanation: https://github.com/Amndeep7/cheetah-debugging/tree/cdd3030480224a6157b5cd388829c0b25a156412

Please see below for an example of me triggering the bug:

![Screen Recording 2020-05-20 at 8 07 39 PM](https://user-images.githubusercontent.com/2015821/82509623-7122b400-9ad6-11ea-93f9-407981179d51.gif)

**Comment by ota-meshi** [comment]
Perhaps you need to call invalidate. In most cases you should call invalidate if you make any data changes from the script.

```js
    onChange() {
      this.data = (new Array(10)).fill(0).map(i => ({ 'asdf': Math.random() }));
      this.$refs.grid. invalidate()
    },
```

If that doesn't work, you may need $nextTick.

```js
    onChange() {
      this.data = (new Array(10)).fill(0).map(i => ({ 'asdf': Math.random() }));
      this.$nextTick(()=>this.$refs.grid. invalidate())
    },
```

https://future-architect.github.io/cheetah-grid/documents/api/vue/components/CGrid.html#methods

If you still have problems, please let me know.

**Comment by Amndeep7** [comment]
Doing the nextTick + invalidate call worked, thanks!
