### ISSUE TITLE
Question: how to do foreign key joining by AJAX?

### ISSUE THREAD

**Issue by xjlin0** [future-architect/cheetah-grid#249]
It's a GREAT library!  thanks a ton for it. Question: how to do foreign key joining by AJAX?

For example, here is some data from `persons` table, lets say country#56 is US, country#34 is Japan, job#1 is CEO, job#2 is CTO
Name | country_id | job_id
------------ | ------------- | -------------
John | 34 | 1
Mary | 56 | 2

How to make Cheetah-gird to show the following by 3 calls of AJAX to `persons`, `countries` and `jobs` table?
Name | country | job
------------ | ------------- | -------------
John | Japan | CEO
Mary | US | CTO

Thanks again!

**Comment by ota-meshi** [comment]
Thank you for posting this question.

You can give `Promise` to the fields of this grid.
You can probably use this to view the data retrieved with AJAX.

There is a simple demo at the link below.

https://future-architect.github.io/cheetah-grid/documents/api/js/grid_data/using_promises.html#promise-cells
