### ISSUE TITLE
Feature : Transposition

### ISSUE THREAD

**Issue by geoffroymontane** [future-architect/cheetah-grid#250]
Hello,
For a project, I need to be able to transpose rows and columns or, at least, to use row types instead of column types (that is the same thing). Is that possible ?
Thank you,
Geoffroy

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

Hmm... This grid cannot transpose rows and columns.
Probably it takes a lot of work, so I think I won't implement it.
