### ISSUE TITLE
Any plans to add support for hierarchical rows?

### ISSUE THREAD

**Issue by znakeeye** [future-architect/cheetah-grid#251]
Like the `ag-grid` [Tree Data](https://www.ag-grid.com/javascript-grid-tree-data/) feature?

**Comment by ota-meshi** [comment]
Thank you for your question.
Currently, this grid cannot display tree data in a table.

There are no plans to add this feature yet. 
Also, as of now, I'm the only maintainer, so I probably can't add this feature because I don't have time.

**Comment by ota-meshi** [comment]
Support for displaying the tree is now available.

https://future-architect.github.io/cheetah-grid/documents/api/js/column_types/TreeColumn.html

If you have additional requests, please open a new issue.
