### ISSUE TITLE
セルの挙動に関する質問

### ISSUE THREAD

**Issue by RxOxHaru** [future-architect/cheetah-grid#252]
下記の内容の実装イメージが沸きません。
どのように実装したらよいでしょうか？
- ドラッグしてセレクトしたセルに対して値を動的にセットしたいのですが方法ありますでしょうか？
- 各セルのborderのスタイル(dashed,dotted)の変更は可能でしょうか？
- 各セルに追加で独自のプロパティをセットすることは可能でしょうか？

**Comment by ota-meshi** [comment]
こんにちは。

あなたのアプリの具体的イメージが無いので、明確に答えることは難しいですが、以下が回答です。  

> ドラッグしてセレクトしたセルに対して値を動的にセットしたいのですが方法ありますでしょうか？

このグリッドはドラッグ系のイベントを持っていないので難しいですが、MOUSEENTER_CELLなどのイベントを駆使することで実現できるかもしれません。

> 各セルのborderのスタイル(dashed,dotted)の変更は可能でしょうか？

現状ではできません。様々なメソッドをオーバーライドすればできないこともないかもしれませんが、オススメはしません。

> 各セルに追加で独自のプロパティをセットすることは可能でしょうか？

独自プロパティの用途にもよりますが、おそらく不可能だと思います。  
内部的に保持することはできたと思いますが、それを使用して何かすることは不可能だと思うためです。  

私はこのissueを閉じますが、不明点があれば自由に再オープンしてください。
別の質問やバグ報告であれば別のissueを投稿してください。
