### ISSUE TITLE
Some image urls in Columns won't load, others load OK

### ISSUE THREAD

**Issue by mspanish** [future-architect/cheetah-grid#259]
I took a screenshot from Chrome so you could see the errors I get trying to load profile images from Twitter - whereas local images load fine. Could it be that some servers can't handle the variable you are appending to the image url request?

![cheetah](https://user-images.githubusercontent.com/206150/86527898-c0872e80-be4f-11ea-8995-5b1ab3b66ef4.png)

Here's what happens when it tries to call an image with this variable appended from Twitter:

![twitter_url](https://user-images.githubusercontent.com/206150/86528010-cf221580-be50-11ea-8b90-4595d3e2a6fe.png)

Here is the same image with no variable appended

![twitter_appended](https://user-images.githubusercontent.com/206150/86528026-d9441400-be50-11ea-94d0-0ff26fc368c7.png)

**Comment by mspanish** [comment]
This is a problem with Twitter that other people have had with other services

[https://wordpress.org/support/topic/problems-with-cdn-setting-and-twitter-images/](https://wordpress.org/support/topic/problems-with-cdn-setting-and-twitter-images/)

**Comment by mspanish** [comment]
A short term fix is to disable the adding of the timestamps to the images, as seen below.

![fix](https://user-images.githubusercontent.com/206150/86529178-0b5a7380-be5b-11ea-9c24-3bb30164c753.png)

**Comment by ota-meshi** [comment]
Thank you for reporting this issue. I think it's good to fix it in the way you suggested. I will fix this and release it.
