### ISSUE TITLE
grid font size?

### ISSUE THREAD

**Issue by mspanish** [future-architect/cheetah-grid#262]
Hi how do you adjust the font-size for the grid? Or can you only do this 1 column at a time?

**Comment by ota-meshi** [comment]
This grid cannot set the font size alone.
Use the font option to combine the font and font-size and set it as a value that can be applied to the canvas context font.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font
The format is the same as the `font` CSS property format.
https://developer.mozilla.org/en-US/docs/Web/CSS/font

```js
const grid = new cheetahGrid.ListGrid({
  // ...
  font: '16px sans-serif'
  // ...
  header: [
    // ...
    {
      // change for each column.
      style: {font: '16px sans-serif'},
    },
    {
      // change for each cell.
      style: record => ({font: record.foo ?  '16px sans-serif' : '8px sans-serif'}),
    },
    // ...
  ]
  // ...
})

// update
grid.font = '16px sans-serif'
```

https://future-architect.github.io/cheetah-grid/documents/api/js/options/#constructor-options
https://future-architect.github.io/cheetah-grid/documents/api/js/column_styles.html
