### ISSUE TITLE
Question: On hover event cell message

### ISSUE THREAD

**Issue by lkiersey** [future-architect/cheetah-grid#264]
How do i display a message if I hover over a cell, I cant seem to get the event to fire.
Or could you give an example of how to display a cell message when its hovered over rather than clicked.
Thanks,
Lenny

**Comment by lkiersey** [comment]
Okay so I was able to fix this in CSS by overriding the style class
```
.cheetah-grid__tooltip-element__content {
	font-family: Roboto !important;
	font-size: 16px !important;
	font-size: .95rem !important;
	min-height: 1em !important;
	line-height: 1 !important;
	width: 100% !important;
	display: block !important;
	white-space: pre-wrap !important;
	margin: 0 !important;
	box-sizing: border-box !important;
    color: #fff !important;
    overflow:hidden !important;
    overflow-x:hidden !important;
    overflow-y:hidden !important;
}
```

**Comment by ota-meshi** [comment]
Sorry for late reply.
This grid will not be able to display the message with hover.  
Also, this feature is relevant to the overall design, so we have no plans to change it.
