### ISSUE TITLE
Disable row during button action

### ISSUE THREAD

**Issue by lkiersey** [future-architect/cheetah-grid#274]
Is there away to disable a row while a button action function is executing? There is an example for disabling all buttons on a grid but I only want to disable the row that was pressed to prevent multiple presses.

**Comment by ota-meshi** [comment]
Sorry for late reply.
You can give a callback function to the disabled property of the ButtonAction instance. Since a record is passed as an argument, judge each record and return a boolean value.

(I noticed that I didn't document this)
