### ISSUE TITLE
Sorting on date.

### ISSUE THREAD

**Issue by rajivsri** [future-architect/cheetah-grid#276]
Need to display date in dd Mon yy format.  Able to do that with function returning text in that format, but then sorting becomes alphabetical. 

Any way to display text, but sort on the date.

**Comment by ota-meshi** [comment]
Thank you for this issue.

You need to give a function to the sort property and sort by yourself. 
https://future-architect.github.io/cheetah-grid/documents/api/js/advanced_header/column_sort.html#sort-by-column

**Comment by JWesorick** [comment]
It would be nice if there was a way to allow the value of the column be the numeric date and then just have a function to format it for the user.
