### ISSUE TITLE
Select copy / paste whole row

### ISSUE THREAD

**Issue by lateshift** [future-architect/cheetah-grid#289]
Hey!

First thanks for this awesome JS Datagrid 🙏.

Is it possible to select copy & paste whole rows (just like the numbered first column in Excel)? 

Thanks in advance.

Best regards

Jens

**Comment by ota-meshi** [comment]
Thank you for the question.

This grid has the ability to enable range paste, but it cannot be controlled rows.
The user must select a row before copying.

https://future-architect.github.io/cheetah-grid/documents/api/js/options/
https://future-architect.github.io/cheetah-grid/documents/api/js/options/allowRangePaste.html
