### ISSUE TITLE
Related Inquiries about Style Options

### ISSUE THREAD

**Issue by seanpablo53** [future-architect/cheetah-grid#307]
I want to erase the border of the column with the style option.
Is it possible?

**Comment by ota-meshi** [comment]
You can extend the theme to change the borders. You cannot change it with style options.

https://future-architect.github.io/cheetah-grid/documents/api/js/theme.html#extend-theme

**Comment by seanpablo53** [comment]
> You can extend the theme to change the borders. You cannot change it with style options.
> 
> https://future-architect.github.io/cheetah-grid/documents/api/js/theme.html#extend-theme

hum.. ok i got it, and here's a further question. how do I line change caption?

**Comment by ota-meshi** [comment]
Even if you only want to change the caption, set the header property again.

```js
grid.header = [{...}]
```
