### ISSUE TITLE
セルの値変更後のUndoについて

### ISSUE THREAD

**Issue by greenyellowred** [future-architect/cheetah-grid#310]
セルの値を変更後にUndoして元の値に戻す機能はありますか？
もしあれば設定・実装方法をご教授いただけますでしょうか。

**Comment by ota-meshi** [comment]
質問ありがとうございます。
Undo・Redoの機能は持っていません。
Undo・Redoを実現したい場合は、使用側で変更を監視してUndo・Redoを実装する必要があります。
