### ISSUE TITLE
how can I get the row numbers of the checked items?

### ISSUE THREAD

**Issue by fikzit** [future-architect/cheetah-grid#311]
When I use the 'check' columnType, how can I get the checked items of the complete list?

**Comment by ota-meshi** [comment]
You can do that by filtering the records where the field specified in the 'check' column is true to the checked records.

**Comment by fikzit** [comment]
I figured it out, the grid.records object is updated automatically, so with this code you can iterate through all nodes and display the ones that have been checked
`for (i in grid.records) {      
           if (grid.records[i].check === true) {
               alert(grid.records[i].id);
           }
       }    `
