### ISSUE TITLE
Can't edit a column when `field` is defined as a function

### ISSUE THREAD

**Issue by JWesorick** [future-architect/cheetah-grid#326]
See example: https://codepen.io/JWesorick/pen/powXbzY

When a column has the `field` property set to a function and `action` set to `"input"`, that column can no longer be edited.

**Comment by ota-meshi** [comment]
Thank you for the question.
If you want to use function and enable a set of values, you need to use the `get` and `set` properties.

```js
        field: {get:(rec) => rec.fname, set:(rec,val)=>rec.fname=val},
```

Probably the method is not described in the documentation 😅
