### ISSUE TITLE
特定セルの文字色/背景色を変更する

### ISSUE THREAD

**Issue by fujita1106** [future-architect/cheetah-grid#363]
Hi
イベントで取得した値を基に特定セルの背景色や文字色を変更したいです。
文字色/背景色をセル単位で指定する方法をご教授頂きたくお願い致します。

Thanks

**Comment by ota-meshi** [comment]
こんにちは @fujita1106.
「イベントで取得した値」とはなんでしょうか？可能であればサンプルコードを提供していただけますか？

Hi @fujita1106.
What does "イベントで取得した値"(value obtained at the event) mean? Would you please provide sample code?

**Comment by fujita1106** [comment]
listenを使用してセルクリック時に値を取得・代入しています。
値の内容を基にセルの色を変えたいです。
`grid.listen(CLICK_CELL, (...args) => listener(args));`
`const listener = (args) => {`
`    const records = grid.records;`
`    if(records[row]["field"] == "")`
`    {`
`        records[row]["field"] = "value";`
`        //row,fieldで指定したセルの背景色を変更したい。`
`    }`
`};`

thanks

**Comment by ota-meshi** [comment]
Thank you for provide a sample code.

You can change the style (color etc.) for each record by specifying a function in the `style` property of the column definition.
I think you can check for changes in the fields of record and use it to change the color for each cell.

See https://future-architect.github.io/cheetah-grid/documents/api/js/column_styles.html#advanced-column-style

カラム定義の`style`プロパティに関数を指定する事でレコードごとにスタイル（色など）を変更することができます。
レコードのフィールドの変更をチェックし、`style`プロパティに関数を指定する事でセルごとに色を変えることができると思います。

**Comment by fujita1106** [comment]
Thank you for your response.
以下コードで試してみたのですが列の背景色が変わりません
`grid.layout.body[0][col].style = {`
`	textAlign:"center", `
`bgColor: "green"`
`};`
`grid.invalidate();`
styleプロパティ上は背景色が定義されていそうなのですが...
![image](https://user-images.githubusercontent.com/88120855/162862026-bede5e4a-2d63-430e-942e-579faf155157.png)

Sorry to ask such a elementary question.

**Comment by ota-meshi** [comment]
You use the function.

**Comment by ota-meshi** [comment]
Oh It's not. You need to specify it when defining the column. It cannot be rewritten later using the property.

**Comment by fujita1106** [comment]
I got it!
Thanks to you I was able to understand that.
