### ISSUE TITLE
Compatibility for Vue3/Nuxt3

### ISSUE THREAD

**Issue by kurousa** [future-architect/cheetah-grid#399]
I planning migration my apps from vue2 / nuxt2.

So, is this components compatiable for Vue3 / Nuxt3 ?

Thank you.

**Comment by ota-meshi** [comment]
We are using this grid in Vue3.
I don't know much about Nuxt, but I think it's probably compatible.

**Comment by kurousa** [comment]
Sounds good!
I will try :)
