### ISSUE TITLE
vue-cheetah-gridのaction propsにつきまして

### ISSUE THREAD

**Issue by masanori0209** [future-architect/cheetah-grid#400]
こんにちは。

こちらのテーブル描画が速く、お気に入りでよく使わせていただいております。
vue-cheetah-gridの部分で少し気になる点がございまして、
下記リンクのutils.jsの中でnormalizeAction（CGridColumn等のPropsからInlineInputEditorなどのアクションを呼び出せる処理だと推測しております。）についてになります。

こちらのPropsの型がObject, String, Functionの３種類で、Stringでの呼び出しの場合はどのような使用用途をイメージしておりますでしょうか？
normalizeAction内において、Stringの場合に"InlineInputEditor"などを入れるとそのままString型で返却されてしまい、
InlineInputEditorを使うことができず、ObjectやFunction以外での利用についてが不明でございまして、
もし使用例などございましたらご提示いただけますと幸いでございます。

https://github.com/future-architect/cheetah-grid/blob/master/packages/vue-cheetah-grid/lib/c-grid/utils.js#L89

**Comment by ota-meshi** [comment]
issue投稿ありがとうございます。

Vueコンポーネントからactionプロパティの文字列での使用は、`'check'`、`'input'`、`'radio'`を使用する想定でいます。
https://future-architect.github.io/cheetah-grid/documents/api/js/column_actions/#standard-column-action

これらは特に追加のプロパティやロジックを必ずしも必要としないため、複雑なオブジェクトを指定するよりも簡単に使用できるようにしたい意図です。（例えばボタンの場合はどのように振る舞うか、追加で定義する必要があります。）

**Comment by masanori0209** [comment]
ご回答いただきましてありがとうございます。

意図も含めて、上記理解致しました。
細かくドキュメント読み込めておらず、お手数をおかけ致しました。

**Comment by ota-meshi** [comment]
いえ、ドキュメントが不足しているのは理解しているので、もしも改善案があれば是非とも時間のある時にプルリクエストいただけると嬉しいです 😄
