### ISSUE TITLE
'Button/Icon' filter in column header

### ISSUE THREAD

**Issue by anarsitta** [future-architect/cheetah-grid#402]
Hello, as part of my task, it is necessary to add a button or a filter icon to the column header, when clicked, a list would drop out that allows you to filter records.
An example implementation would be like this.
![image](https://user-images.githubusercontent.com/101464281/235894905-0ab37787-3a35-4c30-920e-f8829332785c.png)
![image](https://user-images.githubusercontent.com/101464281/235894822-3c721e85-453a-4c0a-aeea-395dbfaa82fe.png)
After selecting the type of material, you need to display only those records that have the selected type.
However, after spending quite a lot of time with the documentation, as well as looking at a large number of forums, I did not find anything like this in Cg.
Perhaps you can help me?
The question is, is it possible to add a button to the table header and customize my behaviors to it?
It is worth noting that after selecting a specific filter, the button should take on the value of a cross, that is, it should have an additional change event, I believe.

**Comment by ota-meshi** [comment]
The built-in API does not provide headers for filters. We don't have any plans to offer it in the future, as I think it's very difficult to use on mobile.

However, you may be able to implement headers for filters by creating your own class that extends `cheetahGrid.headers.action.BaseAction`.

**Comment by anarsitta** [comment]
It is perfectly. Perhaps you have a more detailed guide on how to create your own extending class?
I think the topic can be considered closed, thanks for the help and quick response!
