### ISSUE TITLE
Move react and react-dom to peerDependencies from dependencies

### ISSUE THREAD

**Issue by acherkashin** [future-architect/cheetah-grid#419]
Recently we've decided to use React version of cheetah-grid as we previously used a vanilla version, it works perfectly for us 👍 

We are using react 18, and noticed in `pnpm-lock.yaml` appeared react-17. 

<img width="686" alt="image" src="https://github.com/future-architect/cheetah-grid/assets/9947582/ff7f0adc-3e30-46a9-b2f3-df7bcd0d2229">

I've looked at `package.json` of `cheetah-grid-react` and noticied that react is specified as dependency there  https://github.com/future-architect/cheetah-grid/blob/bb08d463afa1b0d0ead4ad22be18f09ac98b9ff6/packages/react-cheetah-grid/package.json#L25

I think we should specify react as [peerDependency](https://flaviocopes.com/npm-peer-dependencies/) instead.
Moreover, we should allow react version >= 17.

**Comment by ota-meshi** [comment]
@shibukawa Is it possible to change dependencies?

**Comment by acherkashin** [comment]
@ota-meshi do you want me to send a pull request?

**Comment by ota-meshi** [comment]
Yeah! Pull requests are welcome. Thank you.

**Comment by acherkashin** [comment]
@ota-meshi I've created pull request https://github.com/future-architect/cheetah-grid/pull/420
