### ISSUE TITLE
Vue3 support?

### ISSUE THREAD

**Issue by tanaeakihiko** [future-architect/cheetah-grid#421]
Vue2 has reached End of Life on December 31st, 2023.
Are you going to support Vu3?

**Comment by ota-meshi** [comment]
We are using this library with Vue3.

**Comment by tetsuwanadam** [comment]
I only see installation instruction in [the documentation](https://www.npmjs.com/package/vue-cheetah-grid) for Vue 2.
`import CGrid from "vue-cheetah-grid";

Vue.use(CGrid);`

How can the Vue plugin be installed to work with Vue 3?

**Comment by disarticulate** [comment]
I get errors in vite trying to use this in Vue3.
