### ISSUE TITLE
headerStyleのgridへの反映について

### ISSUE THREAD

**Issue by auks-blue** [future-architect/cheetah-grid#428]
こんばんは。大変便利にライブラリを使わせて頂いております。

headerStyleの変更内容をgridへ即反映させる方法はありますか？

例えば、以下のようにbgColorを設定しgridへ反映させます。

grid.header[0].headerStyle = { bgColor:"#CCE8FF"};

grid.header = grid.headerとする事で、gridへは反映はされたのですが、headerStyleのみの変更を行いたいです。

**Comment by ota-meshi** [comment]
質問ありがとうございます。
現在は `header` の部分的な変更を検知してヘッダーを再処理できるようになっていないことがわかりました。
現時点では`grid.header = grid.header`するハックが必要なようです。

**Comment by auks-blue** [comment]
ご回答ありがとうございます。
今回、headerStyleのみの変更が可能かを確認したのは、gridの列幅を手で変更した後に
grid.header = grid.headerする事で、列幅が初期設定の値に戻ってしまう事が理由でした。

対策として考えたのは、RESIZEイベントでgetColWidthでWidthを覚えておいて、grid.header = grid.header後に
setColWidthで覚えておいたWidthに変更するといった事ですが、他に良いアイディアはあるでしょうか？

**Comment by ota-meshi** [comment]
なるほど、確かにそうですね 😓 

スタイルだけどうにかしたい場合、headerStyleにスタイルを返す関数を定義して、状態によって返すスタイルを変化させるように実装した上で、その状態の変更時に、`invalidate()`等の再描画を呼び出すことでうまく動作するかもしれません。

**Comment by auks-blue** [comment]
カラムの設定に`headerStyle : {}`を実装する事で、`grid.header = grid.header`が無くても、当該カラムのみheaderStyleの変更が反映されるようになりました。
また、DocumentsのThemeのサンプルを見てThemeでも対応が可能かもと思い、以下のように実装した所、望む動作になりました。ありがとうございました。
```
frozenRowsBgColor(args) {
    const {
      row,
      col,
      grid: { frozenRowCount , selection},
    } = args;        
    if ((frozenRowCount - 1 === row) && (selection.range.start.col <= col && selection.range.end.col >= col)) {
      return "#CCE8FF";
    } else {
      return "#e9ecef";
    }
},
```
