### ISSUE TITLE
gridの連番について

### ISSUE THREAD

**Issue by auks-blue** [future-architect/cheetah-grid#429]
こんばんは。

gridに連番を振るために、recordsに連番項目を用意し、1から連番を振っています。
この場合、gridで列をクリックして並び替えを行った場合に、連番項目を1から連番を振り直したいのですが、
何かしら方法はありますでしょうか？

**Comment by ota-meshi** [comment]
`sort`プロパティに関数を指定することで、ソートのロジックを自分で実装できるので、そこで連番を振り直す処理も行うようにするのはどうでしょうか？

https://future-architect.github.io/cheetah-grid/documents/api/js/advanced_header/column_sort.html#:~:text=custom%20sort%20logic-,sort(order%2C%20col%2C%20grid),-%7B%0A%20%20%20%20%20%20%20%20const%20compare

**Comment by auks-blue** [comment]
ご回答ありがとうございます。
>sortプロパティに関数を指定することで、ソートのロジックを自分で実装できるので、そこで連番を振り直す処理も行うようにするのはどうでしょうか？

この場合、sortを行う全てのカラムにソートのロジックを追加する必要がありますので、ソートのロジックを関数にした場合でも、実装時に毎回設定するのが少し手間かなと思います。
ソート時に動作するgrid.listenのイベントがあれば一か所でロジックが記載できるので良いかなと思うのですが、ご検討頂けたらありがたいです。
