### ISSUE TITLE
テキストがセルの領域からあふれた場合の内容の確認方法について

### ISSUE THREAD

**Issue by auks-blue** [future-architect/cheetah-grid#430]
こんばんは。

テキストがセルの領域からあふれた場合の内容の確認方法について、パソコンではtextOverflowでツールチップを表示して確認する方法と列幅を広げて確認する方法があるかと思いますが、タブレット等のモバイル利用の場合、どちらの方法も現状出来ないかと思うのですが、モバイルでも何かしら内容を確認する方法はありますでしょうか？

**Comment by ota-meshi** [comment]
> モバイルでも何かしら内容を確認する方法はありますでしょうか？

クリックイベントなどでダイアログを開くなどの全文を確認できる仕組みを各アプリケーションで実装してもらうぐらいのアイディアしかありませんがどうでしょうか？
Gridで何かするアイディアは今のところありません。。。良い見せ方があるでしょうか🤔

**Comment by auks-blue** [comment]
ご回答ありがとうございます。
>Gridで何かするアイディアは今のところありません。。。良い見せ方があるでしょうか🤔

承知しました。確かにタッチ端末でGrid上ではどう表現すれば良いかわかりませんね。。。
自分が思いついたのはSELECTED_CELLイベントのタイミングでGridの外に選択したセルの全文を表示する仕組みを実装する形ですかね。(Excelの数式バーのような見せ方)
