### ISSUE TITLE
Korean IME Input error

### ISSUE THREAD

**Issue by theRichu** [future-architect/cheetah-grid#56]
Hello,

I've found your awesome project, and considering to use my project.

but I found korean input error when edit columns.
![may-21-2018 14-23-26](https://user-images.githubusercontent.com/4320530/40292030-b292ef6c-5d03-11e8-8b1b-e327c3900548.gif)

My env: 
OS : OSX 10.13.4 (17E202)
Browser:  Chrome 66.0.3359.139 (Official Build) (64-bit)

**Comment by ota-meshi** [comment]
Thank you for this issue!
I will check this problem, so please wait.
If you use a non-standard IME, can you also tell me that IME?

**Comment by theRichu** [comment]
No, I use standard IME on OSX,

I think when compositionend event fired,
input editor is visible and focus is transfered (grid-focus-control composition) from cheetah-grid__small-dialog-input__input composition.
and that cause problem,

So, when some cell is selected (before keydown), focus to input-dialog in advance, and keydown fired, input-dialog turn into show! this strategy may works,

**Comment by ota-meshi** [comment]
Thank you for the suggestion.
Your strategy is very effective, but it is very difficult because you have to redesign all core parts involved in the operation.
Now I am investigating whether there is no timing to move the focus so that it does not affect the IME.
