### ISSUE TITLE
Html in cell

### ISSUE THREAD

**Issue by ConselioCamille** [future-architect/cheetah-grid#57]
Hi,

is it possible to write HTML in a cell ?

thanks

**Comment by ota-meshi** [comment]
thanks for your questions.
This is working with canvas so you can not write html.
Cheetah Grid emphasizes speed even at the expense of the convenience of html.
If you want to use html, I recommend [SlickGrid](https://github.com/6pac/SlickGrid) as individual.

**Comment by ConselioCamille** [comment]
thanks for your reply ! I will use one with VueJs component
