### ISSUE TITLE
In a flexbox based layout canvas height is too tall.

### ISSUE THREAD

**Issue by tmccary9207** [future-architect/cheetah-grid#59]
CGird (<c-grid>)

When use percentage/flexbox based layout the canvas height is being set too tall. The canvas width is correct but height is being calculated incorrectly. Note: This page has multiple div's with flex/percentage height widths set. 

パーセント・フレックスボックスレイアウト専用ページでカンバス高さは高すぎる。カンバスの広さはちょうどいいです。備考：このページマルチDIVあり（フレックス・パーセント）。他のコンポネントはこの問題発生してないです。

div.cheetah-grid 1200x378
div.cheetah-grid canvas 1200x443

**Comment by ota-meshi** [comment]
Thank you for this issue!
I will check this problem, so please wait.

**Comment by tmccary9207** [comment]
I tried my best to reproduce the problem. I tried to get your standalone solution to have the same problem but I couldn't. I thought for certain that it was Cheetah-Grid because all my other components were rendering fine and I had done several tests to see what was causing the odd behavior and found Cheetah-Gird wasn't setting the canvas correctly. I believe the real problem must have been some CSS style that was returning the wrong dimensions. Until I have time to create an example that isn't work related feel free close this issue. Sorry for the inconvenience.

問題を再発生させて頑張ったですけどできなかった。他のコンポネントの表示は大丈夫だったそしていろいろ方をテストしました。その理由でCheetah-Gridのカンバスの高さ・広さは設定は違う見つけた。もしかして他のCSSスタイルはCheetah-Gridで無効な情報に渡した。仕事関係ないの例え作る時間があってればまでこのIssueを閉じしてます。ご迷惑をおかけして申し訳ございません。

**Comment by ota-meshi** [comment]
@tmccary9207 Thank you for rechecked.

OK! If there is a problem, submit a new issue.
