### ISSUE TITLE
Header Caption

### ISSUE THREAD

**Issue by kilho37** [future-architect/cheetah-grid#68]
Hi,

How can I change header's **caption** after rendered.

thanks

**Comment by ota-meshi** [comment]
Thank you for this issue!

Only header caption can not be changed.

Instead, you can change the `header` property later.
You can change the `header` property defined in the constructor with the instance `header` property.

ex.
```js
grid.header = [...]
```

**Comment by tylerdd** [comment]
How can I set the textAlign of header to 'center' instead of default 'left' ?  
The style option can only set textAlign of cells to 'center'

**Comment by tylerdd** [comment]
@ota-meshi

**Comment by ota-meshi** [comment]
@tylerdd Thank you for your question.

Please use the `headerStyle` property.
I recently added [this document](https://future-architect.github.io/cheetah-grid/0.6/demos/usage/column_styles.html#header-style).

**Comment by ota-meshi** [comment]
I close this issue.
If the problem persists please open a new issue.
