### ISSUE TITLE
ヘッダの装飾方法 (How to set styles for headers?)

### ISSUE THREAD

**Issue by yuzo1231** [future-architect/cheetah-grid#70]
https://future-architect.github.io/cheetah-grid/0.6/demos/usage/column_styles.html
ヘッダのスタイル指定はできないんですか？
あればデモ作成してほしいです。

**Comment by ota-meshi** [comment]
以下のドキュメントを追加しました。ヘッダーのスタイルを設定する場合は参照してください。
https://future-architect.github.io/cheetah-grid/0.6/demos/usage/column_styles.html#header-style
