### ISSUE TITLE
Font option

### ISSUE THREAD

**Issue by tylerdd** [future-architect/cheetah-grid#75]
When I set 'headerStyle: {
	textAlign: 'center',
	font: '20px Microsoft Yahei'
}'
The font option wasn't applied
@ota-meshi

**Comment by ota-meshi** [comment]
Thank you for this issue.

Please tell me about your environment.

* What browser are you using?
* Do you use Web fonts or not?
* What OS are you using?

**Comment by tylerdd** [comment]
OS: Window 10
browser: Chrome@67.0.3396.99

**Comment by tylerdd** [comment]
@ota-meshi

**Comment by tylerdd** [comment]
This problem was solved by update to vision 0.6.2. Thank you!

**Comment by ota-meshi** [comment]
I’m happy to solve it! If there is a problem again please open a new issue.
