### ISSUE TITLE
check box in Header Caption

### ISSUE THREAD

**Issue by kilho37** [future-architect/cheetah-grid#76]
Hi.. recently i use your cheetah-grid.

but i have one question.

how to put check box in header caption. not rows...

thanks.

**Comment by ota-meshi** [comment]
@kilho37 Thank you for this issue!
Now you can not draw a checkbox on the header.

This function is very useful, I'd like to attach it, but there is one concern.

If the number of records is large, clicking the checkbox on the header, it will take time to switch the check of all the records.

I'd like to first consider the logic to solve this problem.
