### ISSUE TITLE
RowColor

### ISSUE THREAD

**Issue by kilho37** [future-architect/cheetah-grid#77]
Hi..

I want to change row color easily at once.

But check box, menu, and button cells are not color-coded. right?

thanks.

**Comment by ota-meshi** [comment]
@kilho37 Thank you for opened the issue.

I think that you can do by defining `style` or `theme` with `function`.
https://future-architect.github.io/cheetah-grid/0.6/demos/usage/column_styles.html
https://future-architect.github.io/cheetah-grid/0.6/demos/usage/theme.html

I might make a sample if I have time to work.

**Comment by ota-meshi** [comment]
I added an implementation sample.
https://future-architect.github.io/cheetah-grid/0.9/demos/faq/select_row_color.html
I'm changing some things that do not work well in implementing this, so please use the latest version v0.9.
