### ISSUE TITLE
How to reset sort order

### ISSUE THREAD

**Issue by HidekiSugimoto189** [future-architect/cheetah-grid#82]
Hi..

If you operate in the following order, the display of the sort order will remain.

1. Set display data in Grid and display
1. Select column header and specify sort order
1. Resetting the latest data in Grid

You can reset the sort order by executing the following code, but can not you do it a bit easier?
```
// grid is cheetah-grid object
grid.sortState = {
    col: -1,
    order: undefined
}
```

Thanks.

**Comment by ota-meshi** [comment]
Thank you for this issue.
I'd like to fix it in the next release.
