### ISSUE TITLE
typo in themes/BASIC.js

### ISSUE THREAD

**Issue by HidekiSugimoto189** [future-architect/cheetah-grid#83]
I have found Typo so I will report it.

https://github.com/future-architect/cheetah-grid/blob/master/packages/cheetah-grid/src/js/themes/BASIC.js

hiliteBorderColor -> highlightBorderColor

Thanks.

**Comment by ota-meshi** [comment]
Thank you for this problem.
I made mistakes. . .
I would like to fix it in the next release.
